=== pipigithub/voilet/WebContent/schema/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/books"
	xmlns:tns="http://www.example.org/books" elementFormDefault="qualified">

	<element name="books">
		<complexType>
			<sequence>
				<element name="book" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="name"></element>
							<element name="author"></element>
							<element name="price"></element>
						</sequence>
						<attribute name="addr" type="string">
						</attribute>
					</complexType>
				</element>

			</sequence>

		</complexType>
	</element>



</schema>

=== pipigithub/voilet/WebContent/schema/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns="http://www.example.org/books" 
       xsi:schemaLocation="http://www.example.org/books books.xsd"
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<book addr="sdfs">
		<name>红楼梦</name>
		<author>曹雪芹</author>
		<price>9.9</price>
	</book>
	<book>
		<name>黄瓜的用法</name>
		<author>佳佳</author>
		<price>12.3</price>
	</book>
</books>
